services:
  - docker

script:
  - docker build --build-arg VERSION=$VERSION -t chris13524/angular-cli:$VERSION .

deploy:
  provider: script
  script: bash travis_dockerpush.sh
  on:
    branch: master
  skip_cleanup: true

env:
  global:
    - VERSION=6.2.3
    - DOCKER_USERNAME=chris13524
